version: "2"
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  scss-lint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - javascript
        - ruby
    exclude_paths:
      - 'app/controllers/'
  eslint:
    enabled: true
  fixme:
    enabled: true
  reek:
    enabled: true
    config:
      target_ruby_version: "3.1" # override the default parser with Parser::Ruby31
  rubocop:
    enabled: false
    channel: rubocop-1-56-3
    config:
      target_ruby_version: "3.1" # override the default parser with Parser::Ruby31
exclude_patterns:
  - 'config/'
  - 'db/'
  - 'public/'
  - 'spec/'
  - 'vendor/'
  - 'test/'